[tox]
env_list =
   py310, py311, py312, py313, lint
isolated_build = true

[testenv]
skip_install = true
allowlist_externals = uv
commands_pre =
    uv sync --group dev
commands =
    uv run pytest --asyncio-task-timeout=3600 \
                  --color=yes \
                  --cov=dank_mids \
                  --cov-report html \
                  --cov-report term \
                  --cov-report xml:coverage_{envname}.xml

[testenv:lint]
skip_install = true
allowlist_externals = uv
commands_pre =
    uv sync --only-group mypy
commands =
    uv run --no-sync mypy
